import jwt
import base64
import time

# Your token
token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6Ill5LUd0MUFQb1l0MDZmRTFwLUlscXFyVWNlWjE4RWNoTEUyc3g0YThZeTQiLCJhbGciOiJSUzI1NiIsIng1dCI6ImltaTBZMnowZFlLeEJ0dEFxS19UdDVoWUJUayIsImtpZCI6ImltaTBZMnowZFlLeEJ0dEFxS19UdDVoWUJUayJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9lY2VmYmI2Ni1lNTcxLTRhMDQtYWQzNy04MjQ5MmVkZWM4NjAvIiwiaWF0IjoxNzM5NDQ0MTQyLCJuYmYiOjE3Mzk0NDQxNDIsImV4cCI6MTczOTQ0OTIwNCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhaQUFBQVI3ckNYeGxmR1NEeGNPbUc3anQ3bE92b2tKSGtVZ2tWUFpCRDUyTlV3K1cwS2liVHdPNUx5S013d3g0SWs1Z1FISllWUk1SbzlaWG45OVVORG5pQ0l2TFl2a2dwaXhSeDR2SHd2S1MyMmprPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiRW1haWwtQWNjZXNzIiwiYXBwaWQiOiIyZWM0NmY0Ny03MTkyLTQ3YWYtYjY0MC1mNWNiYjZjYmY4NDkiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6Ikt1bWFyIiwiZ2l2ZW5fbmFtZSI6Ik5pdmVzaCIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjQ5LjI0OS4xNTYuMiIsIm5hbWUiOiJOaXZlc2ggS3VtYXIiLCJvaWQiOiJkMTJlYmNiOC0wMjU5LTQ5NDctYTNmNy1kZjZlNjQxZDM4NGQiLCJwbGF0ZiI6IjgiLCJwdWlkIjoiMTAwMzIwMDM5NzI4MDVFMyIsInJoIjoiMS5BVk1BWnJ2djdISGxCRXF0TjRKSkx0N0lZQU1BQUFBQUFBQUF3QUFBQUFBQUFBQlRBTTFUQUEuIiwic2NwIjoiTWFpbC5SZWFkIG9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiMDAyMDg4MzktYjQ4Zi1kOWZkLWMyZjYtNjQ3NjU5YWRkZjA5Iiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiMzJkRVJwUjdoend4bHV5ZThzTUxuZVBoSHdVRExoakgxR1ZsQzZtZzN1MCIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6ImVjZWZiYjY2LWU1NzEtNGEwNC1hZDM3LTgyNDkyZWRlYzg2MCIsInVuaXF1ZV9uYW1lIjoibml2ZXNoLmt1bWFyQGN5bm90ZWNrLmNvbSIsInVwbiI6Im5pdmVzaC5rdW1hckBjeW5vdGVjay5jb20iLCJ1dGkiOiJFVlY3RlVEclBVZXBEdlNMbHAxYUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX2lkcmVsIjoiMSAxNiIsInhtc19zdCI6eyJzdWIiOiJOTkt5WXo1RTgxdGN1cEQxZ2FpdTRYNWF0MzhWR292amJYNjVEQnkxTFVBIn0sInhtc190Y2R0IjoxMzk4ODQ5NDY2fQ.TYLqRCLStuZoGbPRsz7XWcw6B81rPex3HyFkmimxoxComArrApL2IVaNZ9rO7JA8R7KAoku7bCuKsVJ-EvE2bDMWe9eS4UbgOh4BwZUn9ScKUc6rbkVEdSqxacMfama4yRHxrxafPuUiXY9UT8kRpE36Sq65MONyEu6shHV9MFOEawUPUC2mhpGkZ1XsfYZx0GEs0ObsY_DSEAnONay7rPmoTil7mrs_wugsyFMecpBteJaU-HHNMmCcM36Z4YcnFI9HCb-JDdOjCcds9z-vjHJXa4mKjPx7kIUuAo5PvosmSwwmN15By0oVx6bigzZHD7ywRhbA7ihg2PRX2przoQ"

# Decode the token without verifying the signature
decoded_token = jwt.decode(token, options={"verify_signature": False})

# Extract the expiry time
expiry_time = decoded_token.get("exp")

# Get the current time
current_time = int(time.time())

# Calculate the remaining time (in seconds)
remaining_time_seconds = expiry_time - current_time

if remaining_time_seconds > 0:
    # Convert to minutes and hours
    remaining_minutes = remaining_time_seconds // 60
    remaining_hours = remaining_minutes // 60

    print(f"Token will expire in: {remaining_time_seconds} seconds")
    print(f"Token will expire in: {remaining_minutes} minutes")
    print(f"Token will expire in: {remaining_hours} hours")
else:
    print("Token has already expired!")
